#cloud-config

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common
  - docker.io
  - helm

runcmd:
  # Add Kubernetes GPG key
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg

  # Add Kubernetes repo
  - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" > /etc/apt/sources.list.d/kubernetes.list

  # Update + install K8s tools
  - apt-get update
  - apt-get install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl

  # Docker setup
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ubuntu

  # Kubeadm pre-reqs
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab
  - modprobe br_netfilter
  - sysctl -w net.bridge.bridge-nf-call-iptables=1

  # Init cluster
  - kubeadm init --token=abcdef.0123456789abcdef --pod-network-cidr=10.244.0.0/16
  - journalctl -xe > /home/ubuntu/kubeadm_debug.log

  # Kubeconfig setup
  - mkdir -p /home/ubuntu/.kube
  - cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
  - chown ubuntu:ubuntu /home/ubuntu/.kube/config

  # Apply flannel CNI
  - su - ubuntu -c "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

output:
  all: '| tee -a /var/log/cloud-init-output.log'